version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./auctioneer/docker/Dockerfile
    ports:
    - "8085:8085"
  bidder:
    build:
      context: .
      dockerfile: ./bidder/docker/Dockerfile
    ports:
    - "8728:8728"
