version: "3.9"
services:
  auctioneer:
    build:
      context: .
      dockerfile: ./auctioneer/docker/Dockerfile
    ports:
    - "8085:8085"
  bidder:
    build:
      context: .
      dockerfile: ./bidder/docker/Dockerfile
    ports:
    - "8728:8728"
    depends_on:
    - "auctioneer"
  bidder2:
    environment:
      - ID=kumarbidder
      - DELAY=8
      - VALUE=83288
      - PORT=8729
      - BIDDER_URL=bidder2
    build:
      context: .
      dockerfile: ./bidder/docker/Dockerfile
    ports:
    - "8729:8729"
    depends_on:
    - "auctioneer"
