version: "3.9"
services:
  auctioneer:
    environment:
      - AUCTIONEER_PORT=8085
    build:
      context: .
      dockerfile: ./auctioneer/docker/Dockerfile
    ports:
    - "8085:8085"
  bidder1:
    environment:
      - ID=bidder1
      - DELAY=40
      - VALUE=8323
      - PORT=8728
      - AUCTIONEER_URL=auctioneer
      - AUCTIONEER_PORT=8085
    build:
      context: .
      dockerfile: ./bidder/docker/Dockerfile
    ports:
    - "8728:8728"
    depends_on:
    - "auctioneer"
  bidder2:
    environment:
      - ID=bidder2
      - DELAY=89
      - VALUE=83
      - PORT=8729
      - AUCTIONEER_URL=auctioneer
      - AUCTIONEER_PORT=8085
    build:
      context: .
      dockerfile: ./bidder/docker/Dockerfile
    ports:
    - "8729:8729"
    depends_on:
    - "auctioneer"
